CREATE TABLE `t_order` (
`id` BIGINT(11) NOT NULL PRIMARY KEY AUTO_INCREMENT COMMENT '订单id',
`desc` VARCHAR(200) NOT NULL DEFAULT '' COMMENT '订单描述',
`message_id` VARCHAR(200) NOT NULL COMMENT '订单消息id',
`create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
`update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间'
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

CREATE TABLE `t_broker_message_log` (
`id` VARCHAR(200) NOT NULL PRIMARY KEY COMMENT '消息id',
`message` LONGTEXT COMMENT '订单的JSON字符串',
`try_count` INT(3) NOT NULL DEFAULT 0 COMMENT '重新投递次数',
`status` VARCHAR(3) NOT NULL DEFAULT '0' COMMENT '消息状态：0-发送中，1-发送成功，2-发送失败',
`next_retry_time` DATETIME DEFAULT NULL COMMENT '第二次重新投递消息时间',
`create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
`update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间'
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `t_unique_message_id`(
`message_id` VARCHAR(200) NOT NULL UNIQUE PRIMARY KEY
)ENGINE INNODB DEFAULT CHARSET=UTF8;